# Generated by Django 5.1.6 on 2025-03-05 11:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('manager_id', models.IntegerField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_id', models.IntegerField()),
                ('categories_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_firstname', models.CharField(max_length=50)),
                ('customer_lastname', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=20)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('food_item_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=20)),
                ('sell_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=50)),
                ('cost_price', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('purchased_date', models.DateField()),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50)),
                ('quantities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('staff_username', models.CharField(max_length=50)),
                ('staff_firstname', models.CharField(max_length=50)),
                ('staff_lastname', models.CharField(max_length=50)),
                ('staff_email', models.EmailField(max_length=50)),
                ('staff_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('staff_img', models.ImageField(blank=True, upload_to='')),
                ('staff_role', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
            ],
        ),
    ]
