# Generated by Django 5.1.6 on 2025-03-10 10:59

import adminside.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_firstname', models.CharField(max_length=50)),
                ('customer_lastname', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=20)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('food_item_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=20)),
                ('sell_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales_reports',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50)),
                ('quantities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_img', models.ImageField(blank=True, default='staff_images/default.jpg', null=True, upload_to='staff_images/')),
                ('staff_fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('staff_email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('staff_role', models.CharField(choices=[('Manager', 'Manager'), ('Waiter', 'Waiter'), ('Chef', 'Chef'), ('admin', 'admin')], max_length=50)),
                ('staff_phone', models.CharField(max_length=15)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'staff_role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='adminside.branch'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('supplier_phone', models.CharField(max_length=10, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_members', to='adminside.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=50)),
                ('cost_price', models.IntegerField()),
                ('purchased_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('Done', 'Payment Done'), ('Pending', 'Payment Pending')], default='Pending', max_length=10)),
                ('supplier', models.ForeignKey(blank=True, default=adminside.models.get_default_supplier, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.supplier')),
            ],
        ),
    ]
