# Generated by Django 5.1.6 on 2025-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_remove_categories_id_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categories_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales_reports',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_img',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
