# Generated by Django 5.1.6 on 2025-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='food_item_id',
            new_name='purchase_id',
        ),
    ]
