# Generated by Django 5.1.6 on 2025-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_rename_food_item_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
