# Generated by Django 5.1.6 on 2025-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_rename_staff_firstname_staff_staff_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_img',
            field=models.ImageField(blank=True, default='staff_images/default.jpg', null=True, upload_to='staff_images/'),
        ),
    ]
