# Generated by Django 5.1.6 on 2025-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_staff_staff_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Waiter', 'Waiter'), ('Chef', 'Chef')], max_length=50),
        ),
    ]
