# Generated by Django 5.1.6 on 2025-03-06 10:39

import adminside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_alter_staff_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(max_length=15, validators=[adminside.models.validate_phone]),
        ),
    ]
