# Generated by Django 5.1.6 on 2025-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_alter_inventory_exp_date_alter_inventory_mfg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
