# Generated by Django 5.1.6 on 2025-03-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_staff_groups_staff_is_superuser_staff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
