# Generated by Django 5.1.6 on 2025-03-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_fooditem_category_fooditem_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
    ]
