# Generated by Django 5.1.6 on 2025-03-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_alter_staff_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='adminside.branch'),
        ),
    ]
