# Generated by Django 5.1.6 on 2025-03-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_remove_branch_status_branch_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='id',
            new_name='branch_id',
        ),
    ]
