# Generated by Django 5.1.6 on 2025-03-12 09:54

import adminside.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_remove_inventory_branch_remove_inventory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_reports',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='sales_reports',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='sales_reports',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sales_reports',
            name='quantities',
        ),
        migrations.AddField(
            model_name='sales_reports',
            name='category',
            field=models.ForeignKey(default=adminside.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='adminside.categories'),
        ),
        migrations.AddField(
            model_name='sales_reports',
            name='name',
            field=models.CharField(default='Unknown Item', max_length=50),
        ),
        migrations.AddField(
            model_name='sales_reports',
            name='quantity_sold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales_reports',
            name='sold_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales_reports',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
