# Generated by Django 5.1.6 on 2025-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_rename_id_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
