# Generated by Django 5.1.6 on 2025-03-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_rename_product_id_sales_reports_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
    ]
