# Generated by Django 5.1.6 on 2025-03-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_remove_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.branch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
