# Generated by Django 5.1.6 on 2025-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_fooditem_branch_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
