# Generated by Django 5.1.7 on 2025-03-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0019_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
