# Generated by Django 5.1.7 on 2025-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_alter_inventory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='food_item',
            field=models.CharField(max_length=100),
        ),
    ]
