# Generated by Django 5.1.7 on 2025-04-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0022_alter_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
    ]
