# Generated by Django 5.1.7 on 2025-04-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0023_alter_customer_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='adminside.branch'),
            preserve_default=False,
        ),
    ]
