# Generated by Django 5.1.6 on 2025-03-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0015_rename_product_id_sales_reports_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('ordered_items', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.table')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('order_list', models.ManyToManyField(to='staffside.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.table')),
            ],
        ),
    ]
