# Generated by Django 5.1.6 on 2025-03-18 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_rename_product_id_sales_reports_id_and_more'),
        ('staffside', '0003_rename_price_order_total_price_remove_order_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='adminside.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
