# Generated by Django 5.1.6 on 2025-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0004_order_branch_order_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
