# Generated by Django 5.1.6 on 2025-03-18 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0005_remove_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='order_list',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='table',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffside.order'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
