# Generated by Django 5.1.6 on 2025-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0006_remove_sales_order_list_remove_sales_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
