# Generated by Django 5.1.6 on 2025-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0007_remove_order_total_price_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
