# Generated by Django 5.1.7 on 2025-03-25 12:29

import staffside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0012_remove_notification_seen_notificationseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='time',
            field=models.TimeField(default=staffside.models.get_ist_time),
        ),
    ]
