# Generated by Django 5.1.7 on 2025-03-25 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0013_alter_sales_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
