# Generated by Django 5.1.7 on 2025-03-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0015_alter_sales_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='time',
        ),
    ]
