# Generated by Django 5.1.7 on 2025-03-25 13:15

import staffside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0016_remove_sales_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='time',
            field=models.TimeField(default=staffside.models.get_ist_time),
        ),
    ]
